services:
  - type: web
    name: UrbanTrack-Web
    env: node
    repo: https://github.com/Sixomacanda/DSW02A1_TECH_NEXUS.git
    branch: AmahleNgcobo
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: "production"
    dockerfilePath: Dockerfile
